# Generated by Django 4.2.4 on 2024-08-19 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0031_alter_goodsmodel_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webinfo",
            name="background",
        ),
        migrations.CreateModel(
            name="WebInfoImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/")),
                (
                    "webinfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webinfo",
                        to="store.webinfo",
                    ),
                ),
            ],
        ),
    ]
