# Generated by Django 4.2.4 on 2024-08-22 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0033_alter_noticemodel_user_alter_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsmodel",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.webinfoimage",
                verbose_name="banner",
            ),
        ),
        migrations.AddField(
            model_name="webinfoimage",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
