# Generated by Django 4.2.4 on 2024-08-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0034_goodsmodel_banner_webinfoimage_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsmodel",
            name="end_coords",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="goodsmodel",
            name="start_coords",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
